### ISSUE TITLE
Add a means to remove an object from an ORSet

### ISSUE THREAD

**Issue by cblp** [ff-notes/ron#112]
For example, `removeIf :: (Object item -> m Bool) -> m ()` -- remove all objects which obey given predicate.

**Comment by cblp** [comment]
done

**Comment by willbasky** [comment]
There is function already
```
-- | Remove an object reference from the OR-Set
removeRef
    :: (MonadE m, ReplicaClock m, MonadObjectState (ORSet a) m)
    => Object a -> m ()
removeRef = commonRemove . eqRef
```

**Comment by cblp** [comment]
It's not the same, to use `removeRef`, you must to find id first.

**Comment by willbasky** [comment]
When changes will be available on [Hackage](https://hackage.haskell.org/package/ron-rdt)?

**Comment by cblp** [comment]
I'll make a release in a few days.

**Comment by cblp** [comment]
released
