### ISSUE TITLE
Add ability to runStorage with specific identifier

### ISSUE THREAD

**Issue by cblp** [ff-notes/ron#82]
for cases when we cannot guarantee a unique MAC.

And a random id when we even cannot specify one.

**Comment by iupii** [comment]
How we should specify one? By new argument to newHandle? Something like:
```
newHandle :: FilePath -> Maybe Word64 -> IO Handle
newHandle hDataDir hReplicaId = do
...
hReplica <- applicationSpecific <$> (getMacAddress <|> hReplicaId <|> randomId)
...
```

**Comment by cblp** [comment]
@iupii, yes, good idea.

But it would be better to have a separate function, say, `newHandleWithReplica`

**Comment by cblp** [comment]
And there shouldn't be random id in presence of explicit id.

**Comment by iupii** [comment]
With explicit id
```
newHandleWithReplicaId :: FilePath -> Maybe Word64 -> IO Handle
newHandleWithReplicaId hDataDir hReplicaId = do
```
Without
```
newHandle :: FilePath -> IO Handle
newHandle hDataDir = do
...
hReplica <- applicationSpecific <$> fromMaybe getRandomId getMacAddress
```

**Comment by cblp** [comment]
Yes, go for it!

**Comment by iupii** [comment]
Which random library fits?

**Comment by iupii** [comment]
With tf-random
https://github.com/iupii/ron/commit/1c467faf5878d367ae66f5e3832f4d660f78f119

**Comment by cblp** [comment]
PR please

**Comment by cblp** [comment]
Cool, but rewrite (=<<), (<*>) and nested (<$>) with do-notation to lower barrier.

**Comment by cblp** [comment]
done in #107
