### ISSUE TITLE
reduceWireFrame introduces new op ids

### ISSUE THREAD

**Issue by dkellner** [ff-notes/ron#94]
The black box tests in `gritzko~ron-test` even were modified and now differ from the upstream ones at https://github.com/gritzko/ron-test/blob/master/05-rga.out.ron (see commit fdf62dab558fe00a5fed8dedf3d359f0d0b4f9c5).

Is this correct behaviour? Could this (theoretically) lead to a collision when one replica creates op ids for another one?

**Comment by cblp** [comment]
This is only in _chunk version_, and @gritzko removed this field in current RON. Haskell version is slightly outdated. Will it be ok after removing _chunk version_ concept?

**Comment by cblp** [comment]
I want to keep this issue open until the question is fully resolved.

**Comment by dkellner** [comment]
Thanks for the update! I guess it will be fine when these versions are gone altogether. This will happen with RON 2.1 and therefore #41, right?

**Comment by cblp** [comment]
Yes

**Comment by cblp** [comment]
Please review https://reviewable.io/reviews/ff-notes/ron/97

**Comment by cblp** [comment]
fixed in #97
If you have any concern please reopen.
